version: '3.1'

services:
  db:
    container_name: postgres_cafe
    image: 'postgres:latest'
    networks:
      - order-pgsql
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=syspass

  app:
    container_name: spring_cafe
    image: docker-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - order-pgsql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=syspass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

networks:
  order-pgsql:

#volumes:
#  db-data:

