version: '3.8'
services:
  db:
    container_name: postgres_cafe
    image: 'postgres:latest'
    networks:
      - cafe
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=syspass
    # volumes:
    #   - ../../database/postgresql/data:/var/lib/postgresql/data

  app:
    container_name: spring_cafe
    image: docker-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cafe
    depends_on:
      - db


  cloudflared:
    container_name: cloudflared-cafe
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://spring_cafe:8080
    networks:
      - cafe
    ports:
      - '80:80'
    depends_on:
      - app

networks:
  cafe:
    driver: bridge
    name: network-cafe2


    # networks:
    #   - backend
    # depends_on:
    #   - db