version: '3.1'

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://spring_cafe:8080
    networks:
      - my-network
    ports:
      - '80:80'
    depends_on:
      - app

  app:
    container_name: spring_cafe
    image: docker-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network


networks:
  my-network:

